export const GET_FORM = 'GET_FORM';

export const SET_BUILDER_LOADING = 'SET_BUILDER_LOADING';
export const ASSIGN_BUILDER_FORM = 'ASSIGN_BUILDER_FORM';
export const CLEAR_BUILDER_FORM = 'CLEAR_BUILDER_FORM';
export const CREATE_FORM_START = 'CREATE_FORM_START';
export const CREATE_FORM_FAILED = 'CREATE_FORM_FAILED';
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS';

export const SECTION_DELETE_SUCCESS = 'SECTION_DELETE_SUCCESS';
export const SECTION_DELETE_FAILED = 'SECTION_DELETE_FAILED';
export const FIELD_DELETE_SUCCESS = 'FIELD_DELETE_SUCCESS';
export const FIELD_DELETE_FAILED = 'FIELD_DELETE_FAILED';
