export const SET_FETCHING_SC_HEADER = 'SET_FETCHING_SC_HEADER';
export const SET_SC_HEADER_DETAILS = 'SET_SC_HEADER_DETAILS';
export const SET_FETCHING_SC_HIRINGCLIENTS = 'SET_FETCHING_SC_HIRINGCLIENTS';
export const SET_SC_HIRINGCLIENTS = 'SET_SC_HIRINGCLIENTS';
export const SET_SC_HC_ID = 'SET_SC_HC_ID';
export const SET_SC_PAYMENT_STATUS = 'SET_SC_PAYMENT_STATUS';
export const SET_SC_PAYMENT_STATUS_ERROR = 'SET_SC_PAYMENT_STATUS_ERROR';
export const SET_SC_LAST_PAYMENT = 'SET_SC_LAST_PAYMENT';

export const SET_FETCHING_LOCATIONS = 'SET_FETCHING_LOCATIONS';
export const SET_TOTAL_AMOUNT_OF_LOCATIONS = 'SET_TOTAL_AMOUNT_OF_LOCATIONS';
export const SET_LOCATIONS_LIST = 'SET_LOCATIONS_LIST';
export const SET_LOCATIONS_LIST_ERROR = 'SET_LOCATIONS_LIST_ERROR';

export const SET_US_STATES_LIST = 'SET_US_STATES_LIST';
export const SET_CANADIAN_PROVINCES_AND_TERRITORIES_LIST = 'SET_CANADIAN_PROVINCES_AND_TERRITORIES_LIST';
export const SET_COUNTRIES_LIST = 'SET_COUNTRIES_LIST';
export const SET_LOCATIONS_ERROR = 'SET_LOCATIONS_ERROR';
export const SET_SAVING_LOCATION = 'SET_SAVING_LOCATION';
export const SET_PRIMARY_MESSAGE = 'SET_PRIMARY_MESSAGE';
export const SET_CHANGING_PRIMARY = 'SET_CHANGING_PRIMARY';


