export const SET_CERTFOCUS_TASKS_ERROR = 'SET_CERTFOCUS_TASKS_ERROR';
export const SET_CERTFOCUS_FETCHING_TASKS = 'SET_CERTFOCUS_FETCHING_TASKS';
export const SET_CERTFOCUS_TASKS_LIST = 'SET_CERTFOCUS_TASKS_LIST';
export const SET_CERTFOCUS_ROLES_POSSIBLE_VALUES = 'SET_CERTFOCUS_ROLES_POSSIBLE_VALUES';
export const SET_CERTFOCUS_SAVING_TASK_ERROR = 'SET_CERTFOCUS_SAVING_TASK_ERROR';

// TODO these values shouldn't be hardcoded
export const CERTFOCUS_TASK_OPEN_ID = 3;
export const CERTFOCUS_TASK_FINISHED_ID = 2;
export const CERTFOCUS_TASK_PENDING_ID = 1;