export const SET_FETCHING_FILES = 'SET_FETCHING_FILES';
export const SET_DOWNLOADING_FILE = 'SET_DOWNLOADING_FILE';
export const SET_FILES = 'SET_FILES';
export const SET_CONTRACTS_ERROR = 'SET_CONTRACTS_ERROR';
export const SET_TOTAL_AMOUNT_OF_FILES = 'SET_TOTAL_AMOUNT_OF_FILES';
export const SET_SAVING_FILE = 'SET_SAVING_FILE';
export const SET_FILE_URL = 'SET_FILE_URL';
